name: Build APK 
on:
    push:
        branches:
            - master 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: step
              uses: actions/checkout@v4
              
            - name: install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: setup java
              uses: actions/setup-java@v4
              with:
               java-version: 17
               distribution: temurin
            - name: install package 
              run: npm install 
             
            - name: sync android 
              run: |
                 npx cap sync android 
            - name: build APK 
              run: |
                   cd android
                   ./gradlew assembleDebug   