name: Build APK 
on:
    push:
        branches:
            - main 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: step
              uses: actions/checkout@v4
            
              