name: Build APK
on:
    push:
        branches: 
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4
            - name: setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: install package 
              run: npm install 
            - name: Setup java
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: temurin 
            - name: sync android 
              run: npx cap sync android 
            - name: build APK 
              run: |
                   cd android 
                   .gradlew/ assembleDebug
                  
                     